# Generated by Django 3.2 on 2022-11-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20221106_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDIImage',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image'),
        ),
    ]
