# Generated by Django 3.2 on 2022-11-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_prdiimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDPriceDiscount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='discount'),
        ),
    ]
