# Generated by Django 3.2 on 2022-11-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_prdpricediscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDPriceDiscount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='discount'),
            preserve_default=False,
        ),
    ]
