# Generated by Django 3.2 on 2022-11-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_prdpricediscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDNew',
            field=models.BooleanField(default=True),
        ),
    ]
