# Generated by Django 3.2 on 2022-11-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_prdnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDSeller',
            field=models.BooleanField(default=False, verbose_name='Bestseller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDNew',
            field=models.BooleanField(default=True, verbose_name='New-Product'),
        ),
    ]
