# Generated by Django 3.2 on 2022-11-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20221110_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCreated',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
    ]
