# Generated by Django 3.2 on 2022-11-10 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_prdcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCreated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At'),
        ),
    ]
