# Generated by Django 4.1.2 on 2023-01-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_prdcost_alter_product_prdprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCost',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPriceDiscount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='discount'),
        ),
    ]
