# Generated by Django 4.1.2 on 2023-01-25 22:14

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_prdcost_alter_product_prdprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDIs_Active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDIImage',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.image_upload, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDcategory',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Categery'),
        ),
    ]
