# Generated by Django 4.1.5 on 2023-02-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_prdcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDPriceDiscount',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=5, verbose_name='discount'),
        ),
    ]
