# Generated by Django 3.2 on 2022-11-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221115_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
