# Generated by Django 3.2 on 2022-11-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_generalsignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generalsignup',
        ),
    ]
