# Generated by Django 3.2 on 2022-11-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_gsignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GSignup',
        ),
    ]
