# Generated by Django 3.2 on 2022-11-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_gsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalsignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=8)),
                ('password2', models.CharField(max_length=8)),
            ],
        ),
    ]
