# Generated by Django 3.2 on 2022-11-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_generalsignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generalsignup',
        ),
    ]
