# Generated by Django 4.1.5 on 2023-02-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_generalsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
