# Generated by Django 4.1.5 on 2023-02-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_prdis_active_alter_product_prdiimage_and_more'),
        ('accounts', '0014_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='productfavorites',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
