# Generated by Django 4.1.5 on 2023-02-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_prdis_active_alter_product_prdiimage_and_more'),
        ('accounts', '0015_profile_productfavorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='productfavorites',
            field=models.ManyToManyField(blank=True, null=True, to='product.product'),
        ),
    ]
