# Generated by Django 4.1.5 on 2023-02-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderdetails_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='join_date',
            new_name='order_date',
        ),
    ]
