# Generated by Django 4.1.5 on 2023-02-21 05:01

import creditcards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_join_date_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('cardnumber', creditcards.models.CardNumberField(max_length=25, verbose_name='Card Number')),
                ('expire', creditcards.models.CardExpiryField(verbose_name='Exepire Date')),
                ('security', creditcards.models.SecurityCodeField(max_length=4, verbose_name='CCV')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkouts',
            },
        ),
    ]
