# Generated by Django 4.1.5 on 2023-02-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cardholder',
            field=models.CharField(default='', max_length=20, verbose_name='Card Holder'),
            preserve_default=False,
        ),
    ]
