# Generated by Django 4.1.5 on 2023-02-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_checkout_cardholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
