# Generated by Django 4.1.5 on 2023-02-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_checkout_cardnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
    ]
